name: "F5TTS_Base_Chinese"
description: "支持中文的基础F5-TTS模型"
language: ["zh","en"]
model_path: "ckpts/F5TTS_Base/model_1200000.safetensors" # 假设存在这个检查点
vocab_path: "ckpts/F5TTS_Base/vocab.txt" # 假设项目根目录下有vocab.txt
model_cfg_path: "src/f5_tts/configs/F5TTS_Base.yaml"
