name: "F5TTS_v1_Base"
description: "支持中文和英文的基础F5-TTS模型"
language: ["zh","en","ja"]
model_path: "ckpts/F5TTS_v1_Base/model_1250000.safetensors" # 假设存在这个检查点
vocab_path: "ckpts/F5TTS_v1_Base/vocab.txt" # 假设项目根目录下有vocab.txt
model_cfg_path: "src/f5_tts/configs/F5TTS_v1_Base.yaml"
