name: "japanese_multiple_group"
description: "支持manbo日语的F5-TTS模型"
language: ["ja"]
model_path: "ckpts/MaNiang_after/" # 从example_jp.toml获取
vocab_path: "ckpts/ja_manbo_after/vocab.txt" # 从example_jp.toml获取
model_cfg_path: "src/f5_tts/configs/F5TTS_Japanese.yaml" # 从example_jp.toml获取
